version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
       - ./Volume/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


  backend:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ENV: "PRODUCTION"
      # DATABASE
      DATABASE_URL: 'postgres://postgres:1234@postgres/brewery'
      # COMPANY EMAIL
      COMPANY_EMAIL: 'hfa@burundibrewery.com'