# Generated by Django 4.1.3 on 2022-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_member_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Cover Image')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
