# Generated by Django 4.1.3 on 2022-12-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='Facebook',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='Instagram',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='Twitter',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='Youtube',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
