# Generated by Django 4.1.3 on 2022-11-22 15:38

import Job.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=1000)),
                ('Message', models.CharField(max_length=1000000)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpressionOfIntesert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=1000)),
                ('Document', models.FileField(upload_to=Job.models.expression_of_intesert_offer_get_folder_name)),
                ('Actif', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('LimitDayToSubmit', models.DateField()),
                ('Document', models.FileField(upload_to=Job.models.offer_get_folder_name)),
                ('Actif', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=1000)),
                ('Cv', models.FileField(upload_to=Job.models.application_get_folder_name)),
                ('Actif', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Job.offer')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
