# Generated by Django 4.1.3 on 2022-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='CheckEmail',
            field=models.EmailField(default='atibudan2@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
