# Generated by Django 4.1.3 on 2022-11-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_offer_checkemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='Message',
            field=models.TextField(),
        ),
    ]
